--- 

- name: Setup nanoPi M2A as desktop radio
  remote_user: root
  hosts: nanoPi

  tasks:
  - name: update os
    ansible.builtin.apt:
      update_cache: yes
      upgrade: dist

  - name: update dietpi
    ansible.builtin.command:
      cmd: "/boot/dietpi/dietpi-update"

  - name: Install required packages
    ansible.builtin.apt:
      name: "python3,python3-pip,mpd,ncmpc"
      autoremove: yes
      autoclean: yes

  - name: Create 'setpin' script
    copy:
      dest: "/usr/bin/setpin"
      mode: 0755
      content: |
        #!/bin/sh
        pin=$1
        val=$2
        if [ ! -f /sys/class/gpio/gpio$pin/direction ];
        then
          echo $pin > /sys/class/gpio/export || true
        fi
        echo 'out' > /sys/class/gpio/gpio$pin/direction || true
        echo $val > /sys/class/gpio/gpio$pin/value || true

  - name: Put playlist
    copy:
      dest: "/mnt/dietpi_userdata/Music/radio.m3u"
      src: "radio.m3u"

  - name: Load Playlist to mpd
    tags:
      - testing
    shell: |
      /usr/bin/mpc clear
      /usr/bin/mpc load radio.m3u

  - name: Set cronjobs
    tags:
      - testing
    cron:
      name: "Run radio on weekdays"
      minute: 30
      hour: 6
      weekday: "1-5"
      job: "/usr/bin/setpin 62 1 && mpc play 1"

  - name: Set weekend cronjobs
    tags:
      - testing
    cron:
      name: "Run radio on weekend"
      minute: 30
      hour: 9
      weekday: "0,6"
      job: "/usr/bin/setpin 62 1 && mpc play 3"

